apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/blankpge/spring-sensors-tap.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: s
        kind: RabbitmqCluster
        name: rmq-1


